from collections import Counter

from app.schemas import ReportResponse
from app.services.repository import RepositoryService
from app.services.retriever import citation_from_chunk


class GenerationService:
    def __init__(self, repository_service: RepositoryService) -> None:
        self._repository_service = repository_service

    def readme(self, repository_id: str) -> ReportResponse:
        repository = self._repository_service.get(repository_id)
        modules = Counter(chunk.path.split("/")[0] for chunk in repository.chunks)
        language_badges = ", ".join(sorted(repository.languages)) or "source code"
        module_lines = "\n".join(f"- `{name}/`" for name, _ in modules.most_common(12))
        content = (
            f"# {repository.name}\n\n"
            f"{repository.name} is a {language_badges} project indexed by CodePilot.\n\n"
            "## Project Structure\n"
            f"{module_lines or '- No source modules detected'}\n\n"
            "## Development\n"
            "1. Install project dependencies.\n"
            "2. Run the test suite.\n"
            "3. Review the main modules listed above before making changes.\n\n"
            "## Notes Generated by CodePilot\n"
            f"- Indexed files: {repository.files_indexed}\n"
            f"- Indexed chunks: {repository.chunks_indexed}\n"
            f"- Parsed symbols: {len(repository.symbols)}\n"
        )
        citations = [citation_from_chunk(chunk, 1.0) for chunk in repository.chunks[:5]]
        return ReportResponse(
            repository_id=repository.id,
            title=f"README Draft: {repository.name}",
            content=content,
            citations=citations,
        )
